spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.18/face?serverTimezone=UTC&characterEncoding=utf-8&useSSL=False
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  redis:
    host: 192.168.1.18
    port: 6379
server:
  servlet:
    context-path: /face
  port: 8080

dest:
  url: http://111.231.115.97:8000/get_feature
